"""add user role field

Revision ID: 99f30218d7ef
Revises: fc70045eac6e
Create Date: 2026-04-17 10:24:31.273209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99f30218d7ef"
down_revision: Union[str, Sequence[str], None] = "fc70045eac6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可空列
    op.add_column("users", sa.Column("role", sa.String(length=20), nullable=True))
    # 为现有用户设置默认值
    op.execute("UPDATE users SET role = 'viewer' WHERE role IS NULL")
    # 改为非空约束
    op.alter_column("users", "role", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
