"""add file_hash to files table

Revision ID: d56443be650d
Revises: d767cfebee4b
Create Date: 2026-04-17 11:00:24.541850

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d56443be650d"
down_revision: Union[str, Sequence[str], None] = "d767cfebee4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可空列
    op.add_column("files", sa.Column("file_hash", sa.String(length=32), nullable=True))
    # 为现有文件设置临时哈希（基于 ID 生成，确保唯一）
    op.execute("UPDATE files SET file_hash = md5(id::text) WHERE file_hash IS NULL")
    # 改为非空约束
    op.alter_column("files", "file_hash", nullable=False)
    # 创建唯一索引
    op.create_index(op.f("ix_files_file_hash"), "files", ["file_hash"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_files_file_hash"), table_name="files")
    op.drop_column("files", "file_hash")
    # ### end Alembic commands ###
